### ISSUE TITLE
Issue - Upvote Reaction throws an error 

### ISSUE THREAD

**Issue by NekroDarkmoon** [NekroDarkmoon/Zen.js#11]
```
TypeError: Cannot read property 'user' of null
    at MessageReactionAddEvent.handleRep (file:///B:/Projects/Zen/main/events/messageReactionAdd.js:46:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MessageReactionAddEvent.execute (file:///B:/Projects/Zen/main/events/messageReactionAdd.js:26:11)
TypeError: Cannot read property 'user' of null
    at MessageReactionAddEvent.handleRep (file:///B:/Projects/Zen/main/events/messageReactionAdd.js:46:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MessageReactionAddEvent.execute (file:///B:/Projects/Zen/main/events/messageReactionAdd.js:26:11)
TypeError: Cannot read property 'user' of null
    at MessageReactionAddEvent.handleRep (file:///B:/Projects/Zen/main/events/messageReactionAdd.js:46:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MessageReactionAddEvent.execute (file:///B:/Projects/Zen/main/events/messageReactionAdd.js:26:11)
```

Member might need to be fetched for handle rep in both add and remove reaction.

**Comment by NekroDarkmoon** [comment]
Fixed
