### ISSUE TITLE
Issue - [PlayChns] Can't Send Interaction in a deleted channel.

### ISSUE THREAD

**Issue by NekroDarkmoon** [NekroDarkmoon/Zen.js#7]
```
2021-11-19T01:37:17.139Z [error] : Unknown Message
Error [INTERACTION_ALREADY_REPLIED]: The reply to this interaction has already been sent or deferred.
    at CommandInteraction.reply (B:\Projects\Zen\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:89:46)
    at PlayChannels.deleteChn (file:///B:/Projects/Zen/main/commands/playChannels.js:342:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PlayChannels.execute (file:///B:/Projects/Zen/main/commands/playChannels.js:141:9)
    at async InteractionCreateEvent.execute (file:///B:/Projects/Zen/main/events/interactionCreate.js:32:7) {
  [Symbol(code)]: 'INTERACTION_ALREADY_REPLIED'
}
B:\Projects\Zen\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:89
    if (this.deferred || this.replied) throw new Error('INTERACTION_ALREADY_REPLIED');
                                             ^

Error [INTERACTION_ALREADY_REPLIED]: The reply to this interaction has already been sent or deferred.
    at CommandInteraction.reply (B:\Projects\Zen\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:89:46)
    at InteractionCreateEvent.execute (file:///B:/Projects/Zen/main/events/interactionCreate.js:38:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  [Symbol(code)]: 'INTERACTION_ALREADY_REPLIED'
```

Change how sending a reply to the interaction works with the channel was deleted.

**Comment by NekroDarkmoon** [comment]
Fixed.
